sudo: false
language: python
python:
  - "2.7"
cache: pip
install:
  - pip install --upgrade pip
  - pip install coveralls coverage
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - flake8 molo
  - molo scaffold testapp --include molo.polls ^polls/
  - mkdir -p testapp/testapp/templates/core/
  - cp test_settings.py testapp/testapp/settings/local.py
  - cp molo/polls/test_templates/main.html testapp/testapp/templates/core/main.html
  - cp molo/polls/test_templates/section_page.html testapp/testapp/templates/core/section_page.html
  - cp molo/polls/test_templates/base.html testapp/testapp/templates/base.html
  - flake8 testapp
  - pip install -e testapp
  - py.test --cov=molo
after_success:
  - coveralls
before_deploy:
  - pip install twine
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: "OhC+Gp5q95TLQBzWc/tXd9QfVrHtdQCg6fQ+Lo8+RGwkgbwsxU4jDLn9tHnzd8K6nP9WEO4NzcvcNbPEu61P3j3idvlEtrEIuGP+rcZnzQxgm/iLNJYD69mFCtP5Nrk61+nlxftEBEheg1lyJ7fJdxUpe4AQJf9PCRVLcbG/SLNZAZt1QdvD7NND/h9B4WpOMA4sTkmBjzRIV1JQ3uH/o4Ch8hXkwNp38bjR3gg8t35qVklHh08jRGGIimE4pQc5YuuR8Wj6H0tkMFd0szQaBkyRPIERIJbcPVEFclVU9U7xbKTHmZagFbuN9bNeCDNsH6yw05ss98bSY8vmNPs2XcHAQv692Wt7ZWP9W2Z2BStf2EourzJTS0cTZVNd1I5gfMZzKXWnW5UXZ58N5yLHrGISXiAp5om3gOA8R8OAiuDKC/MdG5L0ehMW6UgrB/cZqCMOFMdAcloAO+3VHfqPgNu5J0WfN6dKIrTOYlmhChsWLxThQ0WaPrEB+URfNlFgCEw3buPT2lJmlHkgFLW/lCg1R014zjlW9im8q0beYOTRDmJogh3wt3j5vQeKQcrrAgZiHYNSfLwdqfOdn820BnJ1JeUGh+s4ozOZUe0i5k7W3TMWI8yolgjIIpsCbvV+5s1b6QhK4hMnBVry4uz4bKMPsUqLDT2LUHH2I4761B4="
  on:
    tags: true
    all_branches: true
